/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Connection.ConnectionFactory;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import model.bean.Cliente;
import model.bean.Produto;
import model.dao.ClienteDAO;
import model.dao.ProdutoDAO;


import net.proteanit.sql.DbUtils;

/**
 *
 * @author Fabricio
 */
public class ViewCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCliente
     */
    public ViewCliente() {
        initComponents();
        Date dataSistema = new Date();
        jtdata.setDate(dataSistema);
        readJtableCliente();
        
        
    }
    
    public void readJtableCliente(){
        DefaultTableModel modelo = (DefaultTableModel) jtbcli.getModel();
        modelo.setNumRows(0);
        ClienteDAO dao = new ClienteDAO();
        
        for(Cliente c: dao.listarTodos()){
            
            modelo.addRow(new Object[]{
                c.getIdcliente(),
                c.getNome(),
                c.getTelefone(),
                c.getEndereco(),
            });
            
        }
          
    }
    
    
    public void readJtableForDesc(String desc){
        DefaultTableModel modelo = (DefaultTableModel) jtbcli.getModel();
        modelo.setNumRows(0);
        ClienteDAO dao = new ClienteDAO();
        
        for(Cliente c: dao.buscaPorNome(desc)){
            
            modelo.addRow(new Object[]{
                c.getIdcliente(),
                c.getNome(),
                c.getTelefone(),
                c.getEndereco(),
                
            });
        }
    }
    
    
   /* private void buscaPorNome(){
    
        Connection con = null;
        PreparedStatement preparador = null;
        ResultSet resultado = null;
       
        String sql = "SELECT * FROM cliente WHERE nome LIKE ?";
        
        try{
            con = ConnectionFactory.getConnection();
            preparador = con.prepareStatement(sql);
            preparador.setString(1, jtpesquisar.getText() + "%");
            resultado = preparador.executeQuery();
            jtbcli.setModel(DbUtils.resultSetToTableModel(resultado));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }*/
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtnome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jttelefone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtendereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jbexcluir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtpesquisar = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jbpesquisarcliente = new javax.swing.JButton();
        jtdata = new com.toedter.calendar.JDateChooser();
        idcli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbcli = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Clientes");
        getContentPane().setLayout(null);

        jtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtnomeKeyReleased(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Telefone:");

        jLabel3.setText("Endereço:");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar Campos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jbexcluir.setText("Excluir");
        jbexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexcluirActionPerformed(evt);
            }
        });

        jLabel4.setText("Pesquisar:");

        jtpesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtpesquisarMouseClicked(evt);
            }
        });
        jtpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtpesquisarActionPerformed(evt);
            }
        });
        jtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtpesquisarKeyReleased(evt);
            }
        });

        jButton4.setText("Atualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jbpesquisarcliente.setText("Buscar Cliente");
        jbpesquisarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpesquisarclienteActionPerformed(evt);
            }
        });

        idcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcliActionPerformed(evt);
            }
        });

        jLabel5.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbpesquisarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idcli, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbpesquisarcliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jbexcluir))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 6, 641, 360);

        jtbcli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idcliente", "nome", "telefone", "endereco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbcli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbcliMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbcli);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 410, 637, 120);

        setBounds(0, 0, 673, 576);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Cliente c = new Cliente();
        c.setNome(jtnome.getText());
        c.setEndereco(jtendereco.getText());
        c.setTelefone(jttelefone.getText());
        
        ClienteDAO dao = new ClienteDAO();
        dao.cadastrar(c);
        
        readJtableCliente();
        
       // JOptionPane.showMessageDialog(null, "Cadastrado!");
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jtnome.setText("");
        jttelefone.setText("");
        jtendereco.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtpesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtpesquisarMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtpesquisarMouseClicked

    private void jtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpesquisarKeyReleased
        // TODO add your handling code here:
        
       // buscaPorNome();
    }//GEN-LAST:event_jtpesquisarKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if(jtbcli.getSelectedRow() != -1){
            
            
            
        
           Cliente c = new Cliente();
           c.setIdcliente(Integer.parseInt(idcli.getText()));
           ClienteDAO dao = new ClienteDAO();
           c.setIdcliente((int)jtbcli.getValueAt(jtbcli.getSelectedRow(), 0));
           c.setNome(jtnome.getText());
           c.setTelefone(jttelefone.getText());
           c.setEndereco(jtendereco.getText());
           
          dao.atualizar(c);
          
          readJtableCliente();;
        
        jtnome.setText("");
        jttelefone.setText("");
        jtendereco.setText("");
        
        
        
        JOptionPane.showMessageDialog(null, "Cliente Atualizado!");
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela para atualizar!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexcluirActionPerformed
        // TODO add your handling code here:
        
        if(jtbcli.getSelectedRow() != -1){
            
            
            
        
           Cliente c = new Cliente();
           ClienteDAO dao = new ClienteDAO();
        
           
           c.setIdcliente((int)jtbcli.getValueAt(jtbcli.getSelectedRow(), 0));
          
          
          dao.delete(c);
          
        readJtableCliente();
        
        jtnome.setText("");
        jttelefone.setText("");
        jtendereco.setText("");
        
        
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para a exclusão");
        }
    }//GEN-LAST:event_jbexcluirActionPerformed

    private void idcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcliActionPerformed
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_idcliActionPerformed

    private void jtpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtpesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtpesquisarActionPerformed

    private void jtbcliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbcliMouseClicked
        // TODO add your handling code here:
        
        if(jtbcli.getSelectedRow() != -1){
            idcli.setText(jtbcli.getValueAt(jtbcli.getSelectedRow(),0).toString());
            jtnome.setText(jtbcli.getValueAt(jtbcli.getSelectedRow(),1).toString());
            jttelefone.setText(jtbcli.getValueAt(jtbcli.getSelectedRow(),2).toString());
            jtendereco.setText(jtbcli.getValueAt(jtbcli.getSelectedRow(),3).toString());
        }
    }//GEN-LAST:event_jtbcliMouseClicked

    private void jtnomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtnomeKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtnomeKeyReleased

    private void jbpesquisarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpesquisarclienteActionPerformed
        // TODO add your handling code here:
        
        readJtableForDesc(jtpesquisar.getText());
    }//GEN-LAST:event_jbpesquisarclienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idcli;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbexcluir;
    private javax.swing.JButton jbpesquisarcliente;
    private javax.swing.JTable jtbcli;
    private com.toedter.calendar.JDateChooser jtdata;
    private javax.swing.JTextField jtendereco;
    private javax.swing.JTextField jtnome;
    private javax.swing.JTextField jtpesquisar;
    private javax.swing.JTextField jttelefone;
    // End of variables declaration//GEN-END:variables

}